- name: check if sigar is installed
  shell: ls {{ openhab_install_dir }}/hyperic-sigar-1.6.4-src/bindings/java/sigar-bin/lib/sigar.jar
  ignore_errors: yes
  register: sigar_ls

- name: download sigar
  get_url: >
    url=http://sourceforge.net/projects/sigar/files/sigar/1.6/hyperic-sigar-1.6.4-src.zip
    dest={{ openhab_install_dir }}/hyperic-sigar-1.6.4-src.zip
  when: sigar_ls.rc != 0

- name: unzip sigar
  unarchive: >
    src={{ openhab_install_dir }}/hyperic-sigar-1.6.4-src.zip
    dest={{ openhab_install_dir }}/
    copy=no
  when: sigar_ls.rc != 0

- name: Install ant (needed to build sigar)
  apt: name=ant update_cache=yes
  sudo: true
  when: sigar_ls.rc != 0

- name: Build sigar library
  command: ant
  args: 
    chdir: "{{ openhab_install_dir }}/hyperic-sigar-1.6.4-src/bindings/java"
    creates: "{{ openhab_install_dir }}/hyperic-sigar-1.6.4-src/bindings/java/sigar-bin/lib/sigar.jar"

- name: create openhab lib directory
  file: state=directory path={{ openhab_install_dir }}/runtime/{{openhab_version}}/lib/

- name: link sigar library
  file: >
    state=link
    src={{ openhab_install_dir }}/hyperic-sigar-1.6.4-src/bindings/java/sigar-bin/lib/{{item}}
    dest={{ openhab_install_dir }}/runtime/{{openhab_version}}/lib/{{item}}
  with_items:
    - "sigar.jar"
    - "libsigar-arm-linux.so"